#!/bin/bash
node script_g.js -x 0 -y 0
node script_g.js -x 1 -y 0
node script_g.js -x 2 -y 0
node script_g.js -x 3 -y 0
node script_g.js -x 4 -y 0
node script_g.js -x 5 -y 0
node script_g.js -x 6 -y 0
node script_g.js -x 7 -y 0
node script_g.js -x 8 -y 0
node script_g.js -x 0 -y 1
node script_g.js -x 1 -y 1
node script_g.js -x 2 -y 1
node script_g.js -x 3 -y 1
node script_g.js -x 4 -y 1
node script_g.js -x 5 -y 1
node script_g.js -x 6 -y 1
node script_g.js -x 7 -y 1
node script_g.js -x 8 -y 1
node script_g.js -x 0 -y 2
node script_g.js -x 1 -y 2
node script_g.js -x 2 -y 2
node script_g.js -x 3 -y 2
node script_g.js -x 4 -y 2
node script_g.js -x 5 -y 2
node script_g.js -x 6 -y 2
node script_g.js -x 7 -y 2
node script_g.js -x 8 -y 2
node script_g.js -x 0 -y 3
node script_g.js -x 1 -y 3
node script_g.js -x 2 -y 3
node script_g.js -x 3 -y 3
node script_g.js -x 4 -y 3
node script_g.js -x 5 -y 3
node script_g.js -x 6 -y 3
node script_g.js -x 7 -y 3
node script_g.js -x 8 -y 3
node script_g.js -x 0 -y 4
node script_g.js -x 1 -y 4
node script_g.js -x 2 -y 4
node script_g.js -x 3 -y 4
node script_g.js -x 4 -y 4
node script_g.js -x 5 -y 4
node script_g.js -x 6 -y 4
node script_g.js -x 7 -y 4
node script_g.js -x 8 -y 4
node script_g.js -x 0 -y 5
node script_g.js -x 1 -y 5
node script_g.js -x 2 -y 5
node script_g.js -x 3 -y 5
node script_g.js -x 4 -y 5
node script_g.js -x 5 -y 5
node script_g.js -x 6 -y 5
node script_g.js -x 7 -y 5
node script_g.js -x 8 -y 5
node script_g.js -x 0 -y 6
node script_g.js -x 1 -y 6
node script_g.js -x 2 -y 6
node script_g.js -x 3 -y 6
node script_g.js -x 4 -y 6
node script_g.js -x 5 -y 6
node script_g.js -x 6 -y 6
node script_g.js -x 7 -y 6
node script_g.js -x 8 -y 6
node script_g.js -x 0 -y 7
node script_g.js -x 1 -y 7
node script_g.js -x 2 -y 7
node script_g.js -x 3 -y 7
node script_g.js -x 4 -y 7
node script_g.js -x 5 -y 7
node script_g.js -x 6 -y 7
node script_g.js -x 7 -y 7
node script_g.js -x 8 -y 7
node script_g.js -x 0 -y 8
node script_g.js -x 1 -y 8
node script_g.js -x 2 -y 8
node script_g.js -x 3 -y 8
node script_g.js -x 4 -y 8
node script_g.js -x 5 -y 8
node script_g.js -x 6 -y 8
node script_g.js -x 7 -y 8
node script_g.js -x 8 -y 8
